CREATE USER sa;
ALTER ROLE sa WITH SUPERUSER;
ALTER ROLE sa WITH LOGIN;
ALTER ROLE sa WITH PASSWORD '123';

CREATE USER creatioroot;
ALTER ROLE creatioroot WITH LOGIN;
ALTER ROLE creatioroot WITH PASSWORD '111';
CREATE DATABASE creatio WITH OWNER = creatioroot ENCODING = 'UTF8' 
CONNECTION LIMIT = -1;