CREATE USER serveradmin;
ALTER ROLE serveradmin WITH SUPERUSER;
ALTER ROLE serveradmin WITH LOGIN;
ALTER ROLE serveradmin WITH PASSWORD 'admin';

CREATE USER creatioroot;
ALTER ROLE creatioroot WITH LOGIN;
ALTER ROLE creatioroot WITH PASSWORD 'root';
CREATE DATABASE creatio WITH OWNER = creatioroot ENCODING = 'UTF8' 
CONNECTION LIMIT = -1;